name: country_codes_043
codes:
  - XA-AD
  - XA-AL
  - XA-AT
  - XA-AT-2
  - XA-AT-3
  - XA-AT-4
  - XA-AT-5
  - XA-AT-6
  - XA-AT-7
  - XA-AT-9
  - XA-BA
  - XA-BE
  - XA-BG
  - XA-BY
  - XA-CH
  - XA-CH-VD
  - XA-CZ
  - XA-DE
  - XA-DE-BY
  - XA-DE-SN
  - XA-DK
  - XA-EE
  - XA-ES
  - XA-FI
  - XA-FR
  - XA-GB
  - XA-GB-NIR
  - XA-GR
  - XA-HR
  - XA-HU
  - XA-IE
  - XA-IS
  - XA-IT
  - XA-IT-32
  - XA-LI
  - XA-LT
  - XA-LU
  - XA-LV
  - XA-MC
  - XA-MD
  - XA-ME
  - XA-MK
  - XA-MT
  - XA-NL
  - XA-NO
  - XA-PL
  - XA-PT
  - XA-RO
  - XA-RS
  - XA-RU
  - XA-SI
  - XA-SK
  - XA-SM
  - XA-SE
  - XA-UA
  - XA-VA
  - XB-AM
  - XB-AZ
  - XB-BD
  - XB-CN
  - XB-GE
  - XB-HK
  - XB-ID
  - XB-IL
  - XB-IN
  - XB-IQ
  - XB-IR
  - XB-JP
  - XB-KH
  - XB-KR
  - XB-LB
  - XB-PH
  - XB-PK
  - XB-SA
  - XB-SY
  - XB-TJ
  - XB-TM
  - XB-TR
  - XB-TW
  - XB-UZ
  - XB-VN
  - XC-DZ
  - XC-EG
  - XC-GH
  - XC-GN
  - XC-TN
  - XC-UG
  - XC-ZA
  - XD-AR
  - XD-BO
  - XD-BR
  - XD-CA
  - XD-CL
  - XD-CO
  - XD-CR
  - XD-CU
  - XD-EC
  - XD-GT
  - XD-HN
  - XD-JM
  - XD-MX
  - XD-NI
  - XD-PE
  - XD-PR
  - XD-PY
  - XD-SR
  - XD-TT
  - XD-US
  - XD-UY
  - XD-VE
  - XE-AU
  - XE-NZ
  - XE-PG
