name: language_codes_041
codes:
  - afr
  - alb
  - ara
  - arg
  - arm
  - art
  - aus
  - baq
  - ben
  - bos
  - bul
  - cat
  - cel
  - chi
  - chu
  - cre
  - crp
  - cze
  - dak
  - dan
  - dsb
  - dut
  - eng
  - enm
  - est
  - fao
  - fij
  - fin
  - fre
  - frm
  - fro
  - frr
  - fry
  - fur
  - ger
  - gez
  - gle
  - glg
  - gmh
  - goh
  - grc
  - gre
  - gsw
  - heb
  - hrv
  - hsb
  - hun
  - ice
  - iii
  - ita
  - jpn
  - kor
  - lat
  - lav
  - lit
  - ltz
  - mac
  - mao
  - mon
  - mul
  - nap
  - nds
  - nor
  - oci
  - oji
  - per
  - pol
  - por
  - roa
  - roh
  - rom
  - rum
  - rus
  - sai
  - san
  - scn
  - sco
  - sla
  - slo
  - slv
  - smn
  - spa
  - srp
  - swa
  - swe
  - tat
  - tgl
  - tha
  - tib
  - tsi
  - tur
  - ukr
  - und
  - vie
  - wel
  - wen
  - xal
  - yid
  - zxx
  - zho