
:version:
  :name: tag_config
  :current: 1.0
  :authors: ["Rodolfo Zitellini"]


# Places auth data

:model: place
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "024":
    :master: a
    :indicator: "7#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "1"
    - - "2"
      - :occurrences: "1"
  "034": 
    :master: d
    :indicator: "1#"
    :occurrences: "1"
    :fields: 
    - - d
      - :occurrences: "1"
    - - f
      - :occurrences: "1"
  "040":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - d
      - :occurrences: "?"
    - - e
      - :occurrences: "1"
  "043": 
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - c
      - :occurrences: "*"
  "151":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "?"
  "370":
    :master: c
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - c
      - :occurrences: "?"
    - - e
      - :occurrences: "?"
    - - f
      - :occurrences: "?"
  "451":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "551":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "?"
  "667":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "670": 
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - "0"
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: short_name
    - - b
      - :occurrences: "?"
    - - u
      - :occurrences: "*"
    - - "9"
      - :occurrences: "?"
  "675":
    :master: "w"
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - w
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^w
        :foreign_field: short_name
  "678":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "680":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "856":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - u
      - :occurrences: "?"
    - - z
      - :occurrences: "?"
  "910":
    :master: "0"
    :indicator: "2#"
    :relator_code: "4"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: corporate_name
    - - u
      - :occurrences: "?"
  "981":
    :master: ""
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "1"
    - - d
      - :occurrences: "1"