
:version:
  :name: tag_config
  :current: 1.0
  :authors: ["Rodolfo Zitellini"]


# Places auth data

:model: place
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "024":
    :master: a
    :indicator: "7#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "1"
    - - "2"
      - :occurrences: "1"
  "034": 
    :master: d
    :indicator: "1#"
    :occurrences: "?"
    :fields: 
    - - d
      - :occurrences: "1"
    - - e
      - :occurrences: "1"
    - - f
      - :occurrences: "1"
    - - g
      - :occurrences: "1"
  "040":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - d
      - :occurrences: "?"
    - - e
      - :occurrences: "1"
  "043": 
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - "2"
      - :occurrences: "*"
    - - b
      - :occurrences: "*"
    - - c
      - :occurrences: "*"
  "075": 
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "*"
    - - b
      - :occurrences: "*"
  "151":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - g
      - :occurrences: "1"
  "370":
    :master: "0"
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Place
        :foreign_field: id
        :no_show: true
    - - "4"
      - :occurrences: "?"
    - - c
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
    - - f
      - :occurrences: "?"
  "451":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - g
      - :occurrences: "?"
  "667":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "680":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"