
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: person
:tags:
  "000": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005": 
    :master: ""
    :indicator: "" 
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "007": 
    :master: ""
    :indicator: "" 
    :occurances: "*"
    :fields:
    - - ""
      - :no_browse: true
  "008": 
    :master: ""
    :indicator: ""
    :occurances: "1"
    :fields:
    - - ""
      - :no_browse: true
  "035": 
    :master: a
    :indicator: "##"
    :occurances: "*"    
    :fields: 
    - - a
      - :occurances: "?"
  "039": 
    :master: a
    :indicator: "##"
    :occurances: "*"    
    :fields: 
    - - a
      - :occurances: "?"
  "040": 
    :master: a
    :indicator: "##"
    :occurances: "1"
    :fields: 
    - - a
      - :occurances: "1"
    - - b
      - :occurances: "1"
    - - c
      - :occurances: "1"
    - - d
      - :occurances: "?"

  "043": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "*"
    - - b
      - :occurances: "*"
    - - c
      - :occurances: "*"
  "100": 
    :master: a
    :indicator: "1#"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
    - - d
      - :occurances: "?"
        :browse_inline: true
    - - w
      - :occurances: "?"
        :no_show: true
    - - y
      - :occurances: "?"
  "370": 
    :master: a
    :indicator: "##"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "375": 
    :master: a
    :indicator: "##"
    :occurances: "?"
    :fields: 
    - - a
      - :occurances: "?"
  "400": 
    :master: a
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - d
      - :occurances: "?"
    - - j
      - :occurances: "?"
# This is a linked field
  "509": 
    :master: "0"
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - "0"
      - :occurances: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurances: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - "9"
      - :occurances: "?"
# Reference to institutions
  "510": 
    :master: "0"
    :indicator: "1#"
    :occurances: "*"
    :fields: 
    - - "0"
      - :occurances: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurances: "?"
        :foreign_class: ^0
        :foreign_field: siglum
  "549": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "559": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "569": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"  
    - - j
      - :occurances: "?"  
  "599": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"   
    - - b 
      - :occurances: "?"   
  "667": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
  "670": 
    :master: "0"
    :indicator: "##"
    :occurances: "*"
    :fields:
    - - a
      - :occurances: "?"
    - - b
      - :occurances: "?"
  "678": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - b
      - :occurances: "?"
    - - u
      - :occurances: "?"
  "680": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - i
      - :occurances: "?"
    - - "5"
      - :occurances: "?"
  "684": 
    :master: a
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - a
      - :occurances: "?"
    - - j
      - :occurances: "?"
  "856": 
    :master: u
    :indicator: "##"
    :occurances: "*"
    :fields: 
    - - u
      - :occurances: "?"
    - - y
      - :occurances: "?"
