
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: person
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "024":
    :master: a
    :indicator: "7#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "1"
    - - "2"
      - :occurrences: "1"
  "040":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - d
      - :occurrences: "?"
  "042":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "043":
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - c
      - :occurrences: "*"
  "100":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
    - - c
      - :occurrences: "*"
    - - d
      - :occurrences: "?"
        :browse_inline: true
    - - w
      - :occurrences: "?"
        :no_show: true
    - - y
      - :occurrences: "?"
  "375":
    :master: a
    :indicator: "##"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "400":
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - d
      - :occurrences: "?"
    - - j
      - :occurrences: "?"
# This is a linked field
  "500":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - "i"
      - :occurrences: "?"
  "510":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "1"
        :foreign_class: ^0
        :foreign_field: siglum
  "550":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - i
      - :occurrences: "?"
  "551":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - i
      - :occurrences: "?"

  "599":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - b
      - :occurrences: "?"
  "667":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "670":
    :master: "0"
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - b
      - :occurrences: "?"
  "678":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - b
      - :occurrences: "?"
    - - u
      - :occurrences: "?"
  "680":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - i
      - :occurrences: "?"
    - - "5"
      - :occurrences: "?"
  "710":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: siglum
  "856":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - u
      - :occurrences: "?"
    - - y
      - :occurrences: "?"
