
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# Institution auth data

:model: institution
:tags:
  "000": 
    :master: ""
    :indicator: "" 
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001": 
    :master: ""
    :indicator: "" 
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: false
  "003": 
    :master: ""
    :indicator: "" 
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: false
  "005": 
    :master: ""
    :indicator: "" 
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: false
  "008": 
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "024":
    :master: a
    :indicator: "7#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "1"
    - - c
      - :occurrences: "?"
    - - d
      - :occurrences: "?"
    - - q
      - :occurrences: "*"
    - - z
      - :occurrences: "*"
    - - "0"
      - :occurrences: "?"
    - - "1"
      - :occurrences: "1"
    - - "2"
      - :occurrences: "1"
    - - "6"
      - :occurrences: "?"
    - - "8"
      - :occurrences: "*"
  "034": 
    :master: d
    :indicator: "1#"
    :occurrences: "1"
    :fields: 
    - - d
      - :occurrences: "1"
    - - f
      - :occurrences: "1"
  "040":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - d
      - :occurrences: "?"
  "043": 
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - c
      - :occurrences: "*"
  "110": 
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields: 
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "*"
    - - c
      - :occurrences: "?"
    - - g
      - :occurrences: "?"
        :no_show: true
  "368": 
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "*"
    - - b
      - :occurrences: "*"
    - - c
      - :occurrences: "*"
    - - "2"
      - :occurrences: "?"
  "370": 
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - c
      - :occurrences: "*"
    - - e
      - :occurrences: "*"
    - - f
      - :occurrences: "*"
    - - "2"
      - :occurrences: "?"
  "371": 
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "*"
    - - e
      - :occurrences: "*"
    - - b
      - :occurrences: "*"
    - - c
      - :occurrences: "*"
    - - d
      - :occurrences: "*"
    - - m
      - :occurrences: "*"
    - - s
      - :occurrences: "?"
    - - t
      - :occurrences: "?"
    - - u
      - :occurrences: "*"
    - - v
      - :occurrences: "*"
    - - z
      - :occurrences: "*"
  "372": 
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "*"
    - - "2"
      - :occurrences: "?"
  "410": 
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "*"
  "510": 
    :master: a
    :indicator: "2#"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "1"
    - - i
      - :occurrences: "*"
    - - w
      - :occurrences: "?"
  "551": 
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - "0"
      - :occurrences: "?"
        :foreign_class: Place
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
  "580": 
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - x
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: siglum
  "667": 
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "?"
  "670": 
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - "0"
      - :occurrences: "?"
        :foreign_class: Publication
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: short_name
    - - b
      - :occurrences: "?"
    - - u
      - :occurrences: "*"
    - - "9"
      - :occurrences: "?"
  "678": 
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "?"
  "680": 
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - a
      - :occurrences: "?"
  "700":
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - "0"
      - :occurrences: "?"
        :foreign_class: Person
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: full_name
    - - d
      - :occurrences: "?"
        :browse_inline: true
        :foreign_class: ^0
        :foreign_field: life_dates
        :foreign_alternates: alternate_dates
        #:no_browse: true
    - - "e"
      - :occurrences: "*"
    - - "t"
      - :occurrences: "?"
    - - "4"
      - :occurrences: "*"
        :browse_inline: true
        #:no_browse: true
    - - "5"
      - :occurrences: "?"
        :no_browse: true
  "710": 
    :master: "0"
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - "0"
      - :occurrences: "?"
        :foreign_class: Institution
        :foreign_field: id
        :no_show: true
    - - a
      - :occurrences: "?"
        :foreign_class: ^0
        :foreign_field: name
  "856": 
    :master: u
    :indicator: "1#"
    :occurrences: "*"
    :fields: 
    - - u
      - :occurrences: "?"
    - - z
      - :occurrences: "?"

