
:version:
  :name: tag_config
  :current: 1.0
  :authors: ["Rodolfo Zitellini"]


# Places auth data

:model: place
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "024":
    :master: a
    :indicator: "7#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "1"
    - - "2"
      - :occurrences: "1"
  "040":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "1"
    - - b
      - :occurrences: "1"
    - - c
      - :occurrences: "1"
    - - d
      - :occurrences: "?"
    - - e
      - :occurrences: "1"
  "151":
    :master: a
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - a
      - :occurrences: "?"
  "370":
    :master: c
    :indicator: "##"
    :occurrences: "1"
    :fields:
    - - c
      - :occurrences: "?"
    - - f
      - :occurrences: "?"
  "451":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "667":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "678":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "680":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"