
# Version 2 - For SOLR and Muscat 3
# Note: the default store type is TEXT
# WHich means it is tokenized
# For facets and untokenized filtering
# use string (or integer)

config:
    :version: 2.0
    :model: holding

fields:  
  "001":
  "852a":
  "852b":
  "852c":
      :store: true
  "852d":
  "852e":
  "852q":
  "852z":

