--- 
- :id: Default
  :name: Default
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutDefault
  :filter: 
    default: true
- :id: Show
  :name: Show
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutShow
  :filter: 
    show_all: false
    show: true

# Configuration for person
- :id: DefaultPerson
  :name: Default Person
  :model: person
  :labels: 
  - PersonBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutDefault
  :filter: 
    default: true
- :id: ShowPerson
  :name: Show Person
  :model: person
  :labels: 
  - PersonBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutShow
  :filter:
    show_all: false
    show: true


- :id: Institution
  :name: institution
  :model: institution
  :labels: 
  - InstitutionBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - InstitutionBasicFormOptions
  :layout: 
  - InstitutionLayoutShow
  :filter:
    default: true 
    show_all: false
    show: true

- :id: Catalogue
  :name: catalogue
  :model: catalogue
  :labels: 
  - CatalogueBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - CatalogueBasicFormOptions
  :layout: 
  - CatalogueLayoutShow
  :filter:
    default: true 
    show_all: false
    show: true



