# config/solr.yml
development:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8985/solr/development" %>
production:
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/production" %>
test: &test
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8888}/solr" %>

