--- !map:Settings 
doc_abbreviations: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: "Abkürzungen"
    en: Abbreviations
doc_aid: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Arbeitshilfen
    en: Aide
doc_cataloguing_collections: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Erfassung von Sammlungen
    en: Cataloging collection and convoluta
doc_functions: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: "Grundätzliche Funktionen"
    en: Basic functions
doc_introduction: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Einleitung
    en: Introduction
doc_masks: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Masken
    en: Cataloging forms
doc_tag_index: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: MARC Tag Index
    en: MARC tag index
doc_templates: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    de: Templates
    en: Templates
"000": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Leader
    fr: Guide
    de: Leader
    en: Leader
"001": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Numero documento RISM
    fr: No. RISM
    de: RISM Dokumentnummer
    en: RISM ID No.
"003": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Identificatore del numero di controllo
    fr: "Identité du numéro de contrôle"
    de: Kontrollnummer-Bezeichnung
    en: Control number identifier
"005": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Data e ora dell'ultima transazione
    fr: "Date/heure de la dernière transaction"
    de: Datum und Zeit der letzten Transaktion
    en: Date and time of last transaction
"043": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Country code
    fr: Country code
    de: Länder-Code
    en: County code
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    c: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Country code
        fr: Country code
        de: Länder-Code  
        en: Country code
"110": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Nome di ente
    fr: "Nom de la collectivité"
    de: "Körperschaftsname"
    en: Institution
  accepts: 
  - "710"
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    a: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Nome di ente
        fr: "Nom de la collectivité"
        de: "Körperschaftsname"
        en: Institution
    b: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Ente subordinato
        fr: "Collectivité subordonnée"
        de: "Untergeordnete Körperschaft"
        en: Subordinate unit
    c: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Place
        fr: Place 
        de: Ort
        en: Place
    g: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Ente subordinato
        fr: "Siglum"
        de: "Sigel"
        en: Siglum
"410": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Name variants
    fr: Name variants
    de: Namensvarianten
    en: Name variants
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    a: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Name variants
        fr: Name variants
        de: Namensvarianten  
        en: Name variants
"622": !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Contact 
    fr: Contact
    de: Kontakt
    en: Contact 
  fields: !map:ActiveSupport::HashWithIndifferentAccess 
    e: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: Address
        fr: Address
        de: Adresse
        en: Address 
    u: !map:ActiveSupport::HashWithIndifferentAccess 
      label: !map:ActiveSupport::HashWithIndifferentAccess 
        it: URL
        fr: URL
        de: URL
        en: URL

main: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Registrazioni principali
    fr: "Entrées principales"
    de: Haupteintragungen
    en: Main entry fields
codes: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Numeri e codici
    fr: "Numéros et codes"
    de: Nummern und Codes
    en: Numbers and code fields
control: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    fr: "Champs de contrôle"
    de: Kontrollfelder
    ot: Campi di controllo
    en: Control Fields
notes: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Note
    fr: Notes
    de: Fussnoten
    en: Note fields
other: !map:ActiveSupport::HashWithIndifferentAccess 
  label: !map:ActiveSupport::HashWithIndifferentAccess 
    it: Varia
    fr: Divers
    de: Verschiedenes
    en: Miscellaneous

