--- !map:Settings 
show_unknown_group_warning: false
group_order: 
- main_work
groups:   
  main_work: 
    all_tags: 
    - "001"
    - "003"
    - "005"
    - "008"
    - "024"
    - "035"
    - "040"
    - "042"
    - "043"
    - "065"
    - "075"
    - "079"
    - "100"
    - "130"
    - "377"
    - "380"
    - "382"
    - "383"
    - "384"
    - "400"
    - "430"
    - "500"
    - "530"
    - "548"
    - "550"
    - "667"
    - "670"
    - "675"
    - "678"
    - "912"
    - "913"