--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"008": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"024": 
  layout: 
    fields:
    - - "0" 
    - - a
    - - "2"
"035": 
  layout: 
    fields: 
    - - a
    - - z
    - - "9"
"040": 
  layout: 
    fields: 
    - - b
    - - e
    - - "9"
    - - a
    - - c
    - - d
"042": 
  layout: 
    fields: 
    - - a
"043": 
  layout: 
    fields: 
    - - a
    - - c
"056": 
  layout: 
    fields: 
    - - a
"065": 
  layout: 
    fields:
    - - "2"
    - - a
"075": 
  layout: 
    fields: 
    - - b
    - - "2"
"079": 
  layout: 
    fields: 
    - - a
    - - b
    - - q
    - - u
    - - v
"100":
  layout: 
    fields: 
    - - a
      - type: gnd_work_person
        preserve_foreign_value: true
        editor_partial: subfield_autocomplete
    - - d
      - autocomplete_extra: life_dates
    - - m
    - - n
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "100r"
    - - t
  tag_params:
      100r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"130":
  layout:
    fields:
    - - "a"
"377": 
  layout: 
    fields: 
    - - a
    - - "2"
"380": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_form
        preserve_foreign_value: true
        editor_partial: subfield_autocomplete
    - - "0"
    - - "2"
"382": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_instrument
        preserve_foreign_value: true
        editor_partial: subfield_autocomplete
    - - "9"
    - - "0"
    - - "2"
    - - v
    - - n
    - - s
"383": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
"384": 
  layout: 
    fields: 
    - - a
"400":
  layout: 
    fields: 
    - - a
      - type: gnd_work_person
        preserve_foreign_value: true
        editor_partial: subfield_autocomplete
    - - d
      - autocomplete_extra: life_dates
    - - m
    - - n
    - - r
    - - t
    - - p
"500": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_person
        preserve_foreign_value: true
        editor_partial: subfield_autocomplete
    - - d
    - - e
    - - "0"
    - - "4"
    - - i
    - - w
    - - "9"
    - - t
    - - n
    - - p
    - - r
"530": 
  layout: 
    fields: 
    - - a
    - - "0"
    - - "4"
    - - i
    - - w
"540": 
  layout: 
    fields: 
    - - a
"548": 
  layout: 
    fields: 
    - - a
    - - "4"
    - - i
    - - w
    - - "9"
"550": 
  layout: 
    fields: 
    - - a
"667": 
  layout: 
    fields: 
    - - "5"
    - - a
"670": 
  layout: 
    fields: 
    - - a
    - - b
    - - u
"675": 
  layout: 
    fields: 
    - - a
"678": 
  layout: 
    fields: 
    - - b
"912": 
  layout: 
    fields: 
    - - a
"913": 
  layout: 
    fields: 
    - - a
    - - "0"
    - - i
