--- !map:Settings 
force_editor_ordering: true
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"008": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"024": 
  layout: 
    fields:
    - - "0" 
      - read_only: true
    - - a
      - read_only: true
    - - "2"
      - read_only: true
  tag_params: 
    no_delete: true
"035": 
  layout: 
    fields: 
    - - a
      - read_only: true
    - - z
      - read_only: true
    - - "9"
      - read_only: true
  tag_params: 
    no_delete: true
"040": 
  layout: 
    fields: 
    - - b
      - read_only: true
    - - e
      - read_only: true
    - - "9"
      - read_only: true
    - - a
      - read_only: true
    - - c
      - read_only: true
    - - d
      - read_only: true
  tag_params: 
    no_delete: true
"042": 
  layout: 
    fields: 
    - - a
      - read_only: true
  tag_params: 
    no_delete: true
"043": 
  layout: 
    fields: 
    - - c
      - editor_partial: subfield_select_codes
        select_label: "Country"
        shared_codes: "country_codes_043"
  tag_params:
    no_delete: true
"065": 
  layout: 
    fields:
    - - "2"
      - read_only: true
    - - a
      - read_only: true
  tag_params: 
    no_delete: true
"075": 
  layout: 
    fields: 
    - - b
      - read_only: true
    - - "2"
      - read_only: true
  tag_params: 
    no_delete: true
"079": 
  layout: 
    fields: 
    - - q
      - read_only: true
    - - u
      - read_only: true
  tag_params: 
    no_delete: true
"100":
  layout: 
    fields: 
    - - t
    - - a
    - - d
    - - f
    - - m
    - - n
    - - p
    - - r
      #- editor_partial: subfield_select_codes
      #  codes_reference: "100r"
  tag_params:
      100r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"130":
  layout: 
    fields: 
    - - a
    - - f
    - - m
    - - n
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "130r"
  tag_params:
      130r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"377": 
  layout: 
    fields: 
    - - a
      - editor_partial: subfield_select_codes
        shared_codes: "gnd_377"
    - - "2"
      - read_only: true
        default: "iso639-2b"
"380": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_form
        preserve_foreign_value: true
        editor_partial: subfield_secondary #subfield_autocomplete
    - - "2"
      - read_only: true
        default: "gnd"
"382": 
  layout: 
    fields: 
    - - "a"
      - type: gnd_work_instrument
        preserve_foreign_value: true
        editor_partial: subfield_secondary #subfield_autocomplete
    - - n
    - - s
    - - t
    - - v
    - - "2"
      - read_only: true
        default: "gnd"
"383": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
"384": 
  layout: 
    fields: 
    - - a
      - type: gnd_work_keys
        preserve_foreign_value: true
        editor_partial: subfield_secondary
      #- editor_partial: subfield_select_codes
      #  codes_reference: "384r"
  tag_params:
      384r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"400":
  layout: 
    fields:
    - - "4"
      - editor_partial: subfield_select_codes
    - - t
    - - a
    - - d
    - - f
    - - m
    - - n
    - - p
    - - r
    - - "9"
      - default: "v:"
  tag_params:
        codes:
        - abku
        - nafr
        - nasp
        - tmzu
"430": 
  layout: 
    fields:
    - - "4"
      - editor_partial: subfield_select_codes
    - - a
    - - f
    - - m
    - - n
    - - p
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "430r"
  tag_params:
        codes:
        - abku
        - nafr
        - nasp
        - tmzu
        430r:
        - "A"
        - "a"
        - "A|x"
        - "a|x"
        - "A|b"
        - "a|b"
        - "B"
        - "b"
        - "B|b"
        - "b|b"
        - "C"
        - "c"
        - "C|x"
        - "c|x"
        - "C|b"
        - "c|b"
        - "D"
        - "d"
        - "D|x"
        - "d|x"
        - "D|b"
        - "d|b"
        - "E"
        - "e"
        - "E|b"
        - "e|b"
        - "F"
        - "f"
        - "F|x"
        - "f|x"
        - "G"
        - "g"
        - "G|x"
        - "g|x"
        - "G|b"
        - "g|b"
        - "1t"
        - "2t"
        - "3t"
        - "4t"
        - "5t"
        - "6t"
        - "7t"
        - "8t"
        - "9t"
        - "10t"
        - "11t"
        - "12t"
        - "1tt"
        - "2tt"
        - "3tt"
        - "4tt"
        - "5tt"
        - "6tt"
        - "7tt"
        - "8tt"
        - "9tt"
        - "10tt"
        - "11tt"
        - "12tt"
        - "1byz"
        - "2byz"
        - "3byz"
        - "4byz"
        - "5byz"
        - "6byz"
        - "7byz"
        - "8byz"
"500": 
  allow_new: true
  new_window: people
  layout: 
    fields: 
    - - t
    #- - "a"
    #  - type: gnd_work_person
    #    #preserve_foreign_value: true
    #    editor_partial: subfield_secondary
    - - "0"
      - default: "(DE-588)"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - "9"
      - default: "v:"
    #- - n
    #- - p
    #- - r
  tag_params:
    relator_codes:
      - anla
      - arra
      - aut1
      - auta
      - autf
      - bear
      - chre
      - comp
      - dich
      - druc
      - feie
      - grav
      - hers
      - hrsg
      - illu
      - istm
      - kom1
      - koma
      - kopi
      - kue1
      - kuen
      - libr
      - malr
      - nach
      - obal
      - obpa
      - regi
      - rela
      - saen
      - saml
      - spon
      - spre
      - stif
      - them
      - uebe
      - urhe
      - vbal
      - verr
      - vorg
      - vorl
      - werk
      - widm
"530": 
  layout: 
    fields: 
    - - t
    - - "0"
      - default: "(DE-588)"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - "9"
      - default: "v:"
  tag_params:
    relator_codes:
      - anla
      - nach
      - vorg
      - obal
      - obpa
      - rela
      - them
      - vbal
      - vorl
      - werk
"540": 
  layout: 
    fields: 
    - - a
"548": 
  layout: 
    fields: 
    - - a
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - "9"
      - default: "v:"
  tag_params:
    relator_codes:
      - datj
      - code: datj
        label: "gnd.datj_erscheinungszeitraum"
      - dats
      - code: dats
        label: "gnd.dats_kompositionszeitraum"
"550": 
  layout: 
    fields: 
    - - "0"
      - default: "(DE-588)"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
    - - '9'
      - default: "v:"
  tag_params:
    relator_codes:
      - anla
      - feie
      - istr
      - obal
      - obin
      - obpa
      - rela
      - spra
      - them
      - vbal
"667": 
  layout: 
    fields:
    - - a
      - default: "RISM NFDI4Culture"
        read_only: true
    - - "5"
      - default: "DE-14"
        read_only: true
"670": 
  layout: 
    fields: 
    - - a
    - - b
    - - u
"675": 
  layout: 
    fields: 
    - - a
"678": 
  layout: 
    fields: 
    - - b
"912": 
  layout: 
    fields: 
    - - a
"913": 
  layout: 
    fields: 
    - - a
      - read_only: true
    - - "0"
      - read_only: true
    - - i
      - read_only: true
