--- !map:ActiveSupport::HashWithIndifferentAccess

'000':
  label: records.leader
'001':
  label: records.rism_id_number
01_codes_artistic:
  label: records.artistic_production
02_codes_performing:
  label: records.performance
'035':
  fields:
    a:
      label: records.local_id_number
  label: records.local_id_number
03_codes_technical:
  label: records.technical_production
04_codes_other:
  label: records.other
'300':
  fields:
    '8':
      label: records.set
    a:
      label: records.format_extent
    b:
      label: records.other_physical_details
    c:
      label: records.dimensions
  label: records.physical_description
'500':
  fields:
    '8':
      label: records.set
    a:
      label: records.general_note_institution
  label: records.general_note_institution
'506':
  fields:
    a:
      label: records.access_restrictions
  label: records.access_restrictions
'518':
  fields:
    a:
      label: records.performer_note
  label: records.note_on_performance
'541':
  fields:
    a:
      label: records.source_of_acquisition_note
    c:
      label: records.method_of_acquisition
    d:
      label: records.date_of_acquisition
    e:
      label: records.accession_number
  label: records.source_of_acquisition_note
'561':
  fields:
    a:
      label: records.provenance_notes
  label: records.provenance_notes
'563':
  fields:
    a:
      label: records.binding_note
  label: records.binding_note
'591':
  fields:
    a:
      label: records.other_shelfmark
  label: records.other_shelfmark
'592':
  fields:
    '8':
      label: records.set
    a:
      label: records.watermark_description
  label: records.watermark_description
'593':
  fields:
    a:
      label: records.type
  label: records.source_type
'599':
  fields:
    a:
      label: records.local_notes_field
  label: records.local_notes_field
'651':
  fields:
    a:
      label: records.location_performance
  label: records.location_performance
'691':
  fields:
    a:
      label: records.bibliographic_reference
    n:
      label: records.number_page
  label: records.bibliographic_reference
'700':
  fields:
    '4':
      label: records.function
    '8':
      label: records.set
    a:
      label: records.name
    d:
      label: records.life_dates
    j:
      label: records.attribution_qualifier
  label: records.additional_personal_name
'710':
  fields:
    '4':
      label: records.function
    '8':
      label: records.set
    a:
      label: records.institution
    b:
      label: records.department
    g:
      label: records.attribution_qualifier
  label: records.additional_institution
'852':
  fields:
    a:
      label: records.library_siglum
    b:
      label: records.department
    c:
      label: records.shelfmark
    d:
      label: records.shelfmark_olim
    e:
      label: records.library
    q:
      label: records.material_held
    u:
      label: general.uri
    z:
      label: records.provenance
  label: records.library_siglum
'856':
  fields:
    u:
      label: records.external_resource
    x:
      label: records.link_type
    z:
      label: records.note_external_resource
  label: records.external_resource_uri
'973':
  fields:
    u:
      label: records.bound_with
  label: records.bound_with
Alleged:
  label: records.alleged
Ascertained:
  label: records.ascertained
Autography:
  label: records.autography
Computer printout:
  label: records.computer_printout
Conjectural:
  label: records.conjectural
Digitalization:
  label: records.digitized_source
Doubtful:
  label: records.doubtful
Engraving:
  label: records.engraving
Facsimile:
  label: records.facsimile
IIIF:
  label: records.iiif_manifest
Lithography:
  label: records.lithography
Misattributed:
  label: records.misattributed
Other:
  label: records.other
Photoreproductive process:
  label: records.photoreproductive_process
Reproduction:
  label: records.reproduction
Transparency:
  label: records.transparency
Typescript:
  label: records.typescript
Typography:
  label: records.typography
Verified:
  label: general.verified
arr:
  label: records.arranger
art:
  label: records.artist
asn:
  label: records.associated_name
aut:
  label: records.author
bnd:
  label: records.binder
bsl:
  label: records.bookseller
ccp:
  label: records.conceptor
chr:
  label: records.choreographer
clb:
  label: records.contributor
cmp:
  label: records.composer_cross_reference
cnd:
  label: records.conductor
cns:
  label: records.censor
com:
  label: records.compiler
cst:
  label: records.costume_designer
ctb:
  label: records.co-composer
dnc:
  label: records.dancer
dnr:
  label: records.donor
doc_abbr_dates:
  label: records.dates
doc_abbr_general:
  label: records.general_abbreviations
doc_abbr_keys:
  label: records.keys
doc_abbr_lang:
  label: records.language_codes
doc_abbr_modes:
  label: records.ecclesiastical_modes
doc_abbr_voices_instr:
  label: records.terms_voices_instruments
doc_abbr_voices_instr2:
  label: general.rism_instrument_abbreviations
doc_abbreviations:
  label: records.abbreviations_terminology
doc_added_entries:
  label: records.added_entry_name
doc_administration:
  label: records.administration
doc_aid:
  label: records.aids
doc_aid_liturgical_feasts:
  label: records.liturgical_festivals
doc_aid_locations:
  label: records.location_on_source
doc_aid_texts_sacred_works:
  label: records.standard_texts_sacred_works
doc_aid_titles_keywords:
  label: records.standardized_titles_subject_headings
doc_aid_transposing_instruments:
  label: records.help_transposing_instruments
doc_bibliographical_reference:
  label: records.references
doc_cat_authorities:
  label: records.authorities
doc_cat_collections:
  label: records.cataloging_collection_convoluta
doc_cat_templates:
  label: records.templates
doc_cataloguing:
  label: records.general_cataloguing_guidelines
doc_content:
  label: records.content
doc_date:
  label: records.dates
doc_diplomatic_title:
  label: records.diplomatic_title
doc_edit_functions:
  label: records.basic_functions
doc_edit_searching:
  label: general.searching
doc_edit_workflow:
  label: general.workflow
doc_editor:
  label: general.using_muscat
doc_digital_objects:
  label: records.digital_objects
doc_incipit:
  label: records.incipits
doc_institutions:
  label: records.institutions
doc_introduction:
  label: records.introduction
doc_library:
  label: records.library_information
doc_linkage:
  label: records.linkage
doc_main_entry_fields:
  label: records.main_entry_fields
doc_masks:
  label: records.cataloging_musical_sources
doc_name_variants:
  label: records.name_variants
doc_numbers:
  label: records.numbers_code_fields
doc_people:
  label: records.people_institutions
doc_performance:
  label: records.performances
doc_personal_names:
  label: records.personal_names
doc_physical_description:
  label: records.material_description
doc_provenance:
  label: records.provenance
doc_references:
  label: records.references
doc_relations:
  label: records.relations
doc_tag_index:
  label: general.index_marc_fields
doc_title:
  label: records.title_content_description
dpt:
  label: records.depositor
dsr:
  label: records.designer
dte:
  label: records.dedicatee
edit_administration:
  label: records.administration
edit_library:
  label: records.library_information_relations
edit_material:
  label: records.material_description
edit_names:
  label: records.people_institutions
edit_references:
  label: records.references_and_notes
edt:
  label: records.editor
egr:
  label: records.engraver
evp:
  label: records.event_place
fmo:
  label: records.former_owner
ill:
  label: records.illustrator
itr:
  label: records.instrumentalist
lbt:
  label: records.librettist
ltg:
  label: records.lithographer
lyr:
  label: records.text_author
oth:
  label: records.other
otm:
  label: records.event_organizer
pat:
  label: records.patron
pbl:
  label: records.publisher
ppm:
  label: records.papermaker
prd:
  label: records.production_personnel
prf:
  label: records.performer
prt:
  label: records.printer
pub:
  label: records.publisher
scr:
  label: records.copyist
show_admin:
  label: records.administration
show_content:
  label: records.content
show_distribution:
  label: records.distribution
show_information:
  label: records.further_information
show_library:
  label: records.library_information
show_links:
  label: records.related_titles
show_material:
  label: records.material_description
show_references:
  label: records.references
show_resources:
  label: records.related_resources
show_summary:
  label: records.summary
show_terms:
  label: records.index_terms
trl:
  label: records.translator
unmatched:
  label: general.unknown_fields
voc:
  label: records.vocalist
