--- !map:Settings 
group_order: 
- edit_library
- edit_names
- edit_material
- edit_references
- edit_administration
groups: 
  edit_administration: 
    all_tags: 
    - "001"

  edit_library: 
    all_tags: 
    - "852"
    - '591'
    - '506'
    - '561'
    - '541'
    - '035'
    - '856'
  edit_names:
    all_tags: 
    - '700'
    - '710'

  edit_material:
    all_tags:
    - '593' 
    - '300'
    - '592'
    - '563'
    - '963'
    - '973'

  edit_references:
    all_tags: 
    - '500'
    - '691'
    - '651'
    - '518'
    - "599"

