--- !map:Settings 
group_order: 
- codes
- identity
- contact
- description
- control
groups:
  codes:
    all_tags:
    - "024"
    - "040"
    - "043"
    - "034"
  identity:
    all_tags:
    - "094"
    - "110"
    - "510"
    - "410"
    - "368"
    - "580"
  contact:
    all_tags:
    - "370"
    - "371"
    - "372"
  description:
    all_tags:
    - "678"
    - "670"
    - "680"
    - "856"
    - "551"
    - "710"
    - "700"
  control: 
    all_tags: 
    - "001"
    - "667"
