--- !map:Settings
client:
  "024":
    tags:
      a: required
  "094":
    tags:
      "a":
        required_if:
          "094": "q"
  "110":
    tags:
      a: mandatory
  "368":
    tags:
      a: mandatory
  "580": 
    tags:
      "0":
        any_of:
          - required
          - not_record_id
  "670":
    tags:
      "0": required
  "710": 
    tags:
      "0":
        any_of:
          - required
          - not_record_id
  "856":
    tags:
      u:
        any_of:
          #- begins_with: "http"
          - validate_url
          - required
      "z": required