--- !map:Settings 
group_order: 
- sigla
- identity
- contact
- description
- control
groups:
  sigla:
    all_tags:
    - "024"
    - "035"
    - "040"
    - "043"
    - "034"
  identity:
    all_tags:
    - "110"
    - "510"
    - "410"
    - "373"
    - "368"
    - "580"
  contact:
    all_tags:
    - "371"
  description:
    all_tags:
    - "680"
    - "678"
    - "670"
    - "856"
    - "551"
    - "710"
    - "700"
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "008"
