--- !map:Settings 
group_order: 
- codes
- identity
- contact
- description
- control
groups:
  codes:
    all_tags:
    - "024"
    - "040"
    - "043"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  identity:
    all_tags:
    - "110"
    - "510"
    - "410"
    - "373"
    - "368"
    - "580"
    all_tag_templates:
      "580": institutions/show_580
  contact:
    all_tags:
    - "371"
    - "034"
    all_tag_templates:
      "034": marc_show/show_map
  description:
    all_tags:
    - "680"
    - "678"
    - "670"
    - "856"
    - "551"
    - "710"
    - "700"
    all_tag_templates:
      "670": people/show_catalogue
      "856": marc_show/show_link
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
    - "008"
    - "667"
