--- !map:ActiveSupport::HashWithIndifferentAccess

'000':
  label: records.leader
'001':
  label: records.rism_id_number
'003':
  label: records.control_number_identifier
'005':
  label: records.date_time_last_transaction
008:
  label: records.date_of_creation
01_codes_artistic:
  label: records.artistic_production
'024':
  fields:
    '0':
      label: records.authority_record_control_number
    '1':
      label: records.real_world_object_uri
    '2':
      label: records.authority_agency
    '6':
      label: records.linkage
    '8':
      label: records.field_link
    a:
      label: records.authority_reference
    c:
      label: records.terms_of_availability
    d:
      label: records.additional_codes
    q:
      label: records.qualifying_information
    z:
      label: records.invalid_standard_number
  label: records.authority_reference
02_codes_performing:
  label: records.performance
'034':
  fields:
    d:
      label: records.longitude
    f:
      label: records.latitude
  label: records.location
03_codes_technical:
  label: records.technical_production
'040':
  fields:
    a:
      label: records.original_cataloging_agency
    b:
      label: records.language_of_cataloging
    c:
      label: records.transcribing_agency
    d:
      label: records.modifying_agency
  label: records.cataloging_agency
'043':
  fields:
    c:
      label: records.country_code
  label: records.country_code
04_codes_other:
  label: records.other
'110':
  fields:
    a:
      label: records.institution
    b:
      label: records.subordinate_unit
    c:
      label: records.place
    g:
      label: records.siglum
  label: records.institution
'368':
  fields:
    a:
      label: records.type_institution
    b:
      label: records.type_of_jurisdiction
    c:
      label: records.other_designation
    "2":
      label: records.source
  label: records.type_institution
'370':
  fields:
    c:
      label: records.associated_country
    e:
      label: records.place_of_residence
    f:
      label: records.other_associated_place
    "2":
      label: records.source_of_term
  label: records.associated_place
'371':
  fields:
    a:
      label: records.street_address
    b:
      label: records.city
    c:
      label: records.county_province
    d:
      label: records.country
    e:
      label: records.postal_code
    m:
      label: general.e_mail
    u:
      label: general.url
    s:
      label: records.start_period
    t:
      label: records.end_period
    v:
      label: records.source_of_information
    z:
      label: records.public_note
  label: records.location_and_address
'372':
  fields:
    a:
      label: records.field_of_activity
    "2":
      label: records.source_of_term
  label: records.field_of_activity
'410':
  fields:
    a:
      label: records.other_form_of_name
  label: records.other_form_of_name
'510':
  fields:
    a:
      label: records.parallel_form
    i:
      label: records.relationship_information
    w:
      label: records.control_subfield
  label: records.parallel_form
'551':
  fields:
    a:
      label: records.place
  label: records.places
'580':
  fields:
    x:
      label: records.now_in
  label: records.now_in
'667':
  fields:
    a:
      label: records.internal_note
  label: records.internal_note
'670':
  fields:
    a:
      label: records.literature
    b:
      label: records.information_found
    u:
      label: general.uri
    "9":
      label: general.source_citation
  label: records.literature
'678':
  fields:
    a:
      label: records.history_institution
  label: records.history_institution
'680':
  fields:
    a:
      label: records.general_note
  label: records.general_note
'700':
  fields:
    a:
      label: records.person
  label: records.person
'710':
  fields:
    a:
      label: records.related_institution
  label: records.related_institution
'856':
  fields:
    u:
      label: records.online_finding_aids
    z:
      label: records.note_external_resource
  label: records.online_finding_aids
Archive:
  label: records.archive
Bookseller:
  label: records.bookseller
Copyist:
  label: records.copyist
Documentation center:
  label: records.documentation_center
H:
  label: records.editor
Institution:
  label: records.institution
Library:
  label: records.library
Museum:
  label: records.museum
Other:
  label: records.other
Papermaker:
  label: records.papermaker
Performer:
  label: records.performer
Printer:
  label: records.printer
Publisher:
  label: records.publisher
Research institute:
  label: records.research_institute
XA-AT:
  label: places.austria
XA-AT-2:
  label: places.austria_carinthia
XA-AT-3:
  label: places.austria_lower_austria
XA-AT-4:
  label: places.austria_upper_austria
XA-AT-5:
  label: places.austria_salzburg
XA-AT-6:
  label: places.austria_styria
XA-AT-7:
  label: places.austria_tyrol
XA-AT-9:
  label: places.austria_vienna
XA-BE:
  label: places.belgium
XA-BG:
  label: places.bulgaria
XA-CH:
  label: places.switzerland
XA-CH-VD:
  label: places.switzerland_vaud
XA-CZ:
  label: places.czech_republic
XA-DE:
  label: places.germany
XA-DE-BY:
  label: places.germany_bavaria
XA-DE-SN:
  label: places.germany_saxony
XA-DK:
  label: places.denmark
XA-EE:
  label: places.estonia
XA-ES:
  label: places.spain
XA-FI:
  label: places.finland
XA-FR:
  label: places.france
XA-GB:
  label: places.uk
XA-GB-NIR:
  label: places.northern_ireland
XA-GR:
  label: places.greece
XA-HR:
  label: places.croatia
XA-HU:
  label: places.hungary
XA-IE:
  label: places.ireland
XA-IS:
  label: places.iceland
XA-IT:
  label: places.italy
XA-IT-32:
  label: places.italy_trentino_alto_adige
XA-LT:
  label: places.lithuania
XA-LU:
  label: places.luxembourg
XA-LV:
  label: places.latvia
XA-MC:
  label: places.monaco
XA-ME:
  label: places.montenegro
XA-MT:
  label: places.malta
XA-NL:
  label: places.netherlands
XA-NO:
  label: places.norway
XA-PL:
  label: places.poland
XA-PT:
  label: places.portugal
XA-RO:
  label: places.romania
XA-RS:
  label: places.serbia
XA-RU:
  label: places.russian_federation
XA-SE:
  label: places.sweden
XA-SI:
  label: places.slovenia
XA-SK:
  label: places.slovakia
XA-UA:
  label: places.ukraine
XA-VA:
  label: places.holy_see
XB-AM:
  label: places.armenia
XB-CN:
  label: places.china
XB-HK:
  label: places.hong_kong
XB-ID:
  label: places.indonesia
XB-IL:
  label: places.israel
XB-IN:
  label: places.india
XB-IR:
  label: places.iran
XB-JP:
  label: places.japan
XB-KH:
  label: places.cambodia
XB-KR:
  label: places.korea
XB-PH:
  label: places.philippines
XB-SA:
  label: places.saudi_arabia
XB-SY:
  label: places.syrian_arab_republic
XB-TR:
  label: places.turkey
XB-TW:
  label: places.taiwan
XB-VN:
  label: places.vietnam
XC-BJ:
  label: places.benin
XC-DZ:
  label: places.algeria
XC-EG:
  label: places.egypt
XC-ZA:
  label: places.south_africa
XD-AR:
  label: places.argentina
XD-BR:
  label: places.brazil
XD-CA:
  label: places.canada
XD-CL:
  label: places.chile
XD-CO:
  label: places.colombia
XD-CU:
  label: places.cuba
XD-EC:
  label: places.ecuador
XD-GT:
  label: places.guatemala
XD-HN:
  label: places.honduras
XD-MX:
  label: places.mexico
XD-PR:
  label: places.puerto_rico
XD-PY:
  label: places.paraguay
XD-TT:
  label: places.trinidad_tobego
XD-US:
  label: places.usa
XD-UY:
  label: places.uruguay
XD-VE:
  label: places.venezuela
XE-AU:
  label: places.australia
XE-NZ:
  label: places.new_zealand
XE-PG:
  label: places.papua_new_guinea
administration:
  label: records.administration
arr:
  label: records.arranger
art:
  label: records.artist
asg:
  label: records.assignee
asn:
  label: records.associated_name
aut:
  label: records.author
bnd:
  label: records.binder
bsl:
  label: records.bookseller
ccp:
  label: records.conceptor
chr:
  label: records.choreographer
clb:
  label: records.collaborator
cmp:
  label: records.composer
cnd:
  label: records.conductor
cns:
  label: records.censor
codes:
  label: records.numbers_code_fields
com:
  label: records.compiler
cph:
  label: records.copyright_holder
ctb:
  label: records.co_composer
contact:
  label: records.contact
control:
  label: records.control_fields
cst:
  label: records.costume_designer
description:
  label: records.description
dnc:
  label: records.dancer
dnr:
  label: records.donor
doc_abbreviations:
  label: records.abbreviations
doc_aid:
  label: records.aide
doc_cataloguing_collections:
  label: records.cataloging_collection_convoluta
doc_edit_functions:
  label: records.basic_functions
doc_introduction:
  label: records.introduction
doc_masks:
  label: records.cataloging_forms
doc_tag_index:
  label: general.marc_tag_index
doc_templates:
  label: records.templates
dte:
  label: records.dedicatee
dst:
  label: records.distributor
ed:
  label: records.edition
edt:
  label: records.editor
egr:
  label: records.engraver
fmo:
  label: records.former_owner
identity:
  label: records.identity
ill:
  label: records.illustrator
itr:
  label: records.instrumentalist
lbt:
  label: records.librettist
lse:
  label: records.licensee
ltg:
  label: records.lithograph
lyr:
  label: records.lyricist
main:
  label: records.main_entry_fields
notes:
  label: records.note_fields
other:
  label: records.miscellaneous
otm:
  label: records.event_organizer
pat:
  label: records.patron
pbl:
  label: records.publisher
ppm:
  label: records.papermaker
prd:
  label: records.production_personnel
prf:
  label: records.performer
prt:
  label: records.printer
scr:
  label: records.scribe
sigla:
  label: records.sigla
trl:
  label: records.translator
tyd:
  label: records.type_designer
voc:
  label: records.vocalist
a:
  label: records.earlier_heading
b:
  label: records.later_heading
d:
  label: records.acronym
f:
  label: records.musical_composition
g:
  label: records.broader_term
h:
  label: records.narrower_term
i:
  label: records.reference_instruction_phrase
n:
  label: records.not_applicable
r:
  label: records.relationship_designation
t:
  label: records.immediate_parent_body