--- !map:Settings 
group_order: 
- codes
- identity
- contact
- description
- control
groups:
  codes:
    all_tags:
    - "024"
    - "040"
    - "043"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  identity:
    all_tags:
    - "094"
    - "110"
    - "510"
    - "410"
    - "368"
    - "580"
  contact:
    all_tags:
    - "370"
    - "371"
    - "372"
    - "034"
    all_tag_templates:
      "034": marc_show/show_map
  description:
    all_tags:
    - "680"
    - "678"
    - "670"
    - "856"
    - "551"
    - "710"
    - "700"
    all_tag_templates:
      "856": marc_show/show_link
      "700": marc_show/show_person
  control: 
    all_tags: 
    - "001"
    - "667"
