--- !map:Settings 
group_order: 
- edit_library
- edit_names
- edit_material
- edit_incipits
- edit_links
- edit_administration
groups: 
  edit_administration: 
    all_tags: 
    - "001"

  edit_library: 
    all_tags: 
    - "100"
    - '245'
    - '246'
    - '260'
    - "650"
    - "690"
    - "691"
    - '856'
    - "852"
    all_tag_templates: 
      "100": marc_show/show_person
      "246": marc_show/show_title_variant  
      "856": marc_show/show_link
      "690": marc_show/show_69x_url
      "691": marc_show/show_69x_url

  edit_names:
    all_tags: 
    - '700'
    - '710'
    all_tag_templates: 
      "700": marc_show/show_person
      "710": marc_show/show_institution 

  edit_material:
    all_tags:
    - "500"
    - "599"
    - '593' 
    - '560'
    - "786"
    - "775"

  edit_incipits: 
    all_tags: 
    - "031"
    all_tag_templates: 
      "031": marc_show/show_incipit

  edit_links:
    all_tags:
    - '773'
    - "930"
    - "931"
    - "932"