--- !map:ActiveSupport::HashWithIndifferentAccess

'000':
  label: records.leader
'001':
  label: records.rism_id_number
'003':
  label: records.control_number_identifier
'005':
  label: records.date_time_last_transaction
'024':
  fields:
    '2':
      label: records.source_number_code
    a:
      label: records.standard_number_code
  label: records.other_standard_identifier
'040':
  fields:
    a:
      label: records.original_cataloging_agency
    b:
      label: records.language_of_cataloging
    c:
      label: records.transcribing_agency
    d:
      label: records.modifying_agency
  label: records.cataloging_source
'042':
  fields:
    a:
      label: records.authentication_code
  label: records.authentication_code
'043':
  fields:
    c:
      label: records.nationality
  label: records.nationality
'100':
  fields:
    a:
      label: records.heading_personal_name
    c:
      label: records.religious_order
    d:
      label: records.years_birth_death
    w:
      label: general.status
    y:
      label: records.other_life_dates
  label: records.heading_personal_name
'370':
  fields:
    a:
      label: records.place_birth
  label: records.associated_place
'375':
  fields:
    a:
      label: records.gender
  label: records.gender
'400':
  fields:
    a:
      label: records.name_variant
    d:
      label: records.life_dates
    j:
      label: records.type_name_variant
  label: records.name_variant
'500':
  fields:
    a:
      label: records.related_personal_name
    y:
      label: records.type_relationship
  label: records.related_personal_name
'510':
  fields:
    a:
      label: records.associated_institution
  label: records.associated_institution
'550':
  fields:
    a:
      label: records.profession_or_function
    i:
      label: records.type
  label: records.profession_or_function
'551':
  fields:
    a:
      label: records.geographic_name
    i:
      label: records.type
  label: records.geographic_name
'667':
  fields:
    a:
      label: records.internal_note
  label: records.internal_note
'670':
  fields:
    a:
      label: records.source_data_found
    b:
      label: records.information_found
  label: records.source_data_found
'678':
  fields:
    a:
      label: records.additional_biographical_information
  label: records.additional_biographical_information
'680':
  fields:
    a:
      label: records.general_note_personal
  label: records.general_note_personal
'856':
  fields:
    u:
      label: records.external_resource_url
    y:
      label: records.note_external_resource
  label: records.external_resource
XA-AT:
  label: places.austria
XA-AT-2:
  label: places.austria_carinthia
XA-AT-3:
  label: places.austria_lower_austria
XA-AT-4:
  label: places.austria_upper_austria
XA-AT-5:
  label: places.austria_salzburg
XA-AT-6:
  label: places.austria_styria
XA-AT-7:
  label: places.austria_tyrol
XA-AT-9:
  label: places.austria_vienna
XA-BE:
  label: places.belgium
XA-BG:
  label: places.bulgaria
XA-CH:
  label: places.switzerland
XA-CH-VD:
  label: places.switzerland_vaud
XA-CZ:
  label: places.czech_republic
XA-DE:
  label: places.germany
XA-DE-BY:
  label: places.germany_bavaria
XA-DE-SN:
  label: places.germany_saxony
XA-DK:
  label: places.denmark
XA-EE:
  label: places.estonia
XA-ES:
  label: places.spain
XA-FI:
  label: places.finland
XA-FR:
  label: places.france
XA-GB:
  label: places.uk
XA-GR:
  label: places.greece
XA-HR:
  label: places.croatia
XA-HU:
  label: places.hungary
XA-IE:
  label: places.ireland
XA-IS:
  label: places.iceland
XA-IT:
  label: places.italy
XA-IT-32:
  label: places.italy_trentino_alto_adige
XA-LT:
  label: places.lithuania
XA-LU:
  label: places.luxembourg
XA-LV:
  label: places.latvia
XA-MC:
  label: places.monaco
XA-MD:
  label: places.moldavia
XA-ME:
  label: places.montenegro
XA-MT:
  label: places.malta
XA-NL:
  label: places.netherlands
XA-NO:
  label: places.norway
XA-PL:
  label: places.poland
XA-PT:
  label: places.portugal
XA-RO:
  label: places.romania
XA-RS:
  label: places.serbia
XA-RU:
  label: places.russian_federation
XA-SE:
  label: places.sweden
XA-SI:
  label: places.slovenia
XA-SK:
  label: places.slovakia
XA-UA:
  label: places.ukraine
XA-VA:
  label: places.holy_see
XB-AM:
  label: places.armenia
XB-CN:
  label: places.china
XB-GE:
  label: places.georgia
XB-IL:
  label: places.israel
XB-IN:
  label: places.india
XB-IQ:
  label: places.iraq
XB-IR:
  label: places.iran
XB-JP:
  label: places.japan
XB-KH:
  label: places.cambodia
XB-KR:
  label: places.korea
XB-SY:
  label: places.syrian_arab_republic
XB-TR:
  label: places.turkey
XB-TW:
  label: places.taiwan
XB-VN:
  label: places.vietnam
XC-BJ:
  label: languages.benin
XC-DZ:
  label: places.algeria
XC-EG:
  label: places.egypt
XC-GN:
  label: places.guinea
XC-ZA:
  label: places.south_africa
XD-AR:
  label: places.argentina
XD-BR:
  label: places.brazil
XD-CA:
  label: places.canada
XD-CL:
  label: places.chile
XD-CO:
  label: places.colombia
XD-CU:
  label: places.cuba
XD-EC:
  label: places.ecuador
XD-HN:
  label: places.honduras
XD-MX:
  label: places.mexico
XD-PE:
  label: places.peru
XD-PR:
  label: places.puerto_rico
XD-PY:
  label: places.paraguay
XD-TT:
  label: places.trinidad_tobego
XD-US:
  label: places.usa
XD-UY:
  label: places.uruguay
XD-VE:
  label: places.venezuela
XE-AU:
  label: places.australia
XE-NZ:
  label: places.new_zealand
administration:
  label: records.administration
bn:
  label: records.nickname
brother of:
  label: records.brother_of
child of:
  label: records.child_of
codes:
  label: records.numbers_code_fields
confused with:
  label: records.confused_with
control:
  label: records.control_fields
da:
  label: records.pseudonym
do:
  label: records.religious_name
doc_abbreviations:
  label: records.abbreviations
doc_aid:
  label: records.aide
doc_cataloguing_collections:
  label: records.cataloging_collection_convoluta
doc_edit_functions:
  label: records.basic_functions
doc_edit_workflow:
  label: general.workflow
doc_editor:
  label: general.editor_help
doc_introduction:
  label: records.introduction
doc_masks:
  label: records.cataloging_forms
doc_tag_index:
  label: general.marc_tag_index
doc_templates:
  label: records.templates
dv:
  label: records.other_variant
ee:
  label: records.married_name
ef:
  label: records.name_family
father of:
  label: records.father_of
female:
  label: general.female
ff:
  label: records.personal_name
gg:
  label: records.birth_name
go:
  label: records.place_birth
ha:
  label: records.place_origin
in:
  label: records.initials
main_person:
  label: records.main_entry_fields
male:
  label: general.male
married to:
  label: records.married_to
mo:
  label: records.monogram
mother of:
  label: records.mother_of
notes:
  label: records.note_fields
other:
  label: records.other
places:
  label: records.countries_places
po:
  label: records.postal_place
references:
  label: records.references_and_notes
related to:
  label: records.related_to
relations:
  label: records.relations
sister of:
  label: records.sister_of
so:
  label: records.place_death
subject:
  label: records.subject_access_fields
tn:
  label: records.baptismal_name
ub:
  label: records.translation
unknown:
  label: records.unknown
variants:
  label: records.name_variants
wl:
  label: records.country_active
wo:
  label: records.place_active
wr:
  label: records.region_active
xx:
  label: records.unknown
z:
  label: records.alternate_spelling
