--- !map:Settings 
group_order: 
- main_place
- variants
- codes
- geodata
- references
- control
groups:   
  main_place: 
    all_tags: 
    - "151"
    - "970"

  variants:
    all_tags:
    - "451"

  geodata:
    all_tags:
    - "043"
    - "370"
    - "034"

  codes: 
    all_tags: 
    - "024"
    - "075"

  references:
    all_tags:
    - "667"
    - "680"
  control: 
    all_tags:
    - "040" 
    - "001"