--- !map:Settings 
group_order: 
- main_place
- codes
- variants
- references
- control
groups:   
  main_place: 
    all_tags: 
    - "151"
    - "370"
  codes: 
    all_tags: 
    - "024"
    - "075"
  variants:
    all_tags:
    - "451"
  references:
    all_tags:
    - "667"
    - "678"
    - "680"
  control: 
    all_tags:
    - "040" 
    - "001"

