--- !map:Settings 
group_order: 
- main
- subject
- notes
- control
groups: 
  main: 
    all_tags: 
    - "100"
    - "700"
    - "240"
    - "730"
    - "260"
    - "300"     
    - "337" 
    - "210"
    - "780"
    - "785"
    all_tag_templates:
      "100": marc_show/show_person
      "700": marc_show/show_person
      "780": marc_show/show_related_publication
      "785": marc_show/show_related_publication
  subject:
    all_tags:
    - "020"
    - "041"
    - "710"
    - "760"
    - "650"
    - "651" 
    - "250"

    all_tag_templates:
      "650": marc_show/show_subject
      "710": marc_show/show_institution
  control: 
    all_tags: 
    - "040"
    - "001"

  notes: 
    all_tags: 
    - "500"
    - "502"
#    - "505"
    - "599"
    - "856"
    - "520"
    - "981"
    - "590"
    all_tag_templates: 
      "856": marc_show/show_link
      "981": marc_show/show_duplicated_from
 
