--- !map:Settings 
group_order: 
- main
- subject
- other
- notes
- control
groups: 
  main: 
    all_tags: 
    - "100"
    - "700"
    - "240"
    - "730"
    - "260"
    - "300"     
    - "337" 
    - "210"
    all_tag_templates:
      "100": marc_show/show_person
      "700": marc_show/show_person
  subject:
    all_tags:
    - "020"
    - "041"
    - "710"
    - "760"
    - "650"
    - "651" 
    - "250"
    - "780"
    - "785"
    all_tag_templates:
      "650": marc_show/show_subject
      "710": marc_show/show_institution
      "780": marc_show/show_related_publication
      "785": marc_show/show_related_publication
  other:
    template: marc_show/show_preceding_publication
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  notes: 
    all_tags: 
    - "500"
    - "502"
    - "599"
    - "856"
    - "520"
    all_tag_templates: 
      "856": marc_show/show_link
 
