--- !map:Settings 
group_order: 
- main
- subject
- notes
- control
groups: 
  main: 
    all_tags: 
    - "100"
    - "700"
    - "710"
    - "240"
    - "250"
    - "730"
    - "260"
    - "300"
    - "760"
    - "780"
    - "785"
    - "337"
    - "210"
  subject:
    all_tags:
    - "020"
    - "022"
    - "024"
    - "041"
    - "044"
    - "650"
    - "651"
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "005"
  notes: 
    all_tags: 
    - "500"
    - "502"
    - "599"
    - "856"
    - "520"
