--- !map:Settings 
group_order: 
- edit_library
- edit_names
- edit_content
- edit_material
- edit_incipits
- edit_references
- edit_works
- edit_administration

group_exclude:
  collection:
  - edit_incipits
  libretto_source:
  - edit_incipits
  libretto_edition_content:
  - edit_incipits
  theoretica_source:
  - edit_incipits
  theoretica_edition_content:
  - edit_incipits

tag_exclude:
  collection:
  - '026'
  - '546'
  - '595'
  - '651'
  - '657'
  - '740'
  - '787'
  edition:
  - '506'
  - '525'
  - '541'
  - '561'
  - '563'
  - '591'
  - '592'
  - '657'
  - '740'
  - '773'
  - '787'
  - '852'
  source:
  - '026'
  - '597'
  - '774'
  - '775'
  edition_content:
  - '506'
  - '525'
  - '541'
  - '561'
  - '563'
  - '591'
  - '592'
  - '740'
  - '774'
  - '852'
  libretto_source:
  - '590'
  - '594'
  - '596'
  - '597'
  - '598'
  - '774'
  - '775'
  - '787'
  libretto_edition_content:
  - '506'
  - '541'
  - '561'
  - '590'
  - '591'
  - '594'
  - '596'
  - '598'
  - '774'
  - '787'
  - '852'
  theoretica_source:
  - '590'
  - '594'
  - '595'
  - '596'
  - '598'
  - '651'
  - '657'
  - '690'
  - '774'
  - '787'
  theoretica_edition_content:
  - '506'
  - '541'
  - '561'
  - '590'
  - '591'
  - '594'
  - '595'
  - '596'
  - '598'
  - '651'
  - '657'
  - '690'
  - '772'
  - '787'
  - '852'
  
tag_exclude_with_holdings:
  collection:
  - '506'
  - '541'
  - '561'
  - '591'
  - '773'
  - '852'

groups:
  edit_library:
    all_tags:
    - '852'
    - '591'
    - '035'
    - '506'
    - '561'
    - '541'
    - '773'
    - '787'
    - '774'
    - '775'
  edit_names:
    all_tags:
    - '100'
    - '700'
    - '710'
    ungrouped_tags:
     "700": 8
     "710": 8
  edit_content:
    all_tags:
    - '245'
    - '246'
    - '240'
    - '690'
    - '383'
    - '730'
    - '650'
    - '520'
    - '594'
    - '598'
    - '597'
    - '595'
    - '740'
    - '041'
    - '546'
    - '026'
  edit_material:
    all_tags:
    - '593'
    - '260'
    - '597'
    - '033'
    - '300'
    - '590'
    - '340'
    - '028'
    - '592'
    - '700'
    - '710'
    - '500'
    - '563'
    - '856'
    subfield_grouping: 8
  edit_incipits:
    all_tags:
    - '031'
    template: show_incipit
  edit_references:
    all_tags:
    - '500'
    - '505'
    - '525'
    - '691'
    - '510'
    - '596'
    - '657'
    - '651'
    - '518'
    - '856'
    ungrouped_tags:
     "500": 8
     "856": 8
  edit_works:
    all_tags:
    - "930"
    editor_only: true
  edit_administration:
    all_tags:
    - '001'
    - '040'
    - '599'
