--- !map:Settings 
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
    no_delete: true
  tag_header: none
"026": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
    - - d
    - - e
"028": 
  layout: 
    fields: 
    - - a
"031": 
  new_window: standard_titles
  new_window_field: title_equals
  layout: 
    fields:
    - - u
      - hidden: true
    - - a
    - - b
    - - c
    - - d
    - - m
    - - e
    - - t
      - growfield: true
        type: standard_title
        field: title
        editor_partial: subfield_secondary
        allow_new: true
        has_links_to: true
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "031r"
    - - n
      - values: 
        - "xF"
        - "xFC"
        - "xFCG"
        - "xFCGD"
        - "xFCGDA"
        - "xFCGDAE"
        - "xFCGDAEB"
        - "bB"
        - "bBE"
        - "bBEA"
        - "bBEAD"
        - "bBEADG"
        - "bBEADGC"
        - "bBEADGCF"
        editor_partial: subfield_autocomplete
    - - o
    - - g
      - editor_partial: subfield_select_codes_grouped
        codes_reference: clef_groups
    - - s
    - - p
      - editor_partial: subfield_pae
    - - q
    - - z
  tag_params:
    031r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b" 
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
    clef_groups:
      01_modern_clefs:
      - C-1
      - C-2
      - C-3
      - C-4
      - C-5
      - F-1
      - F-2
      - F-3
      - F-4
      - F-5
      - G-1
      - G-2
      - G-3
      - G-4
      - G-5
      - g-2
      02_mensural_clefs:
      - C+1
      - C+2
      - C+3
      - C+4
      - C+5
      - F+1
      - F+2
      - F+3
      - F+4
      - F+5
      - G+1
      - G+2
      - G+3
      - G+4
      - G+5
"033": 
  layout: 
    fields: 
    - - indicator
      - editor_partial: subfield_indicator
    - - a
"040": 
  layout: 
    fields:
    - - a
      - hidden: true
    - - d
      - hidden: true 
    - - b
      - cols: 2
        editor_partial: subfield_select_codes
        select_label: "Language"
        codes_reference: "codes"
    columns: 2
  tag_params:
    codes:
      - "eng"
      - "fre"
      - "ger"
      - "ita"
      - "spa"
"041": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
        codes_reference: "codes"
    - - e
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
        codes_reference: "codes"
    - - h
      - cols: 2 
        editor_partial: subfield_select_codes
        select_label: "Language"
        codes_reference: "codes"
    columns: 2
  tag_params:
    codes:
      - "afr"
      - "ara"
      - "arg"
      - "baq"
      - "cat"
      - "chi"
      - "chu"
      - "cze"
      - "dan"
      - "dut"
      - "eng"
      - "enm"
      - "est"
      - "fas"
      - "fin"
      - "fre"
      - "frr"
      - "fry"
      - "ger"
      - "gle"
      - "glg"
      - "gmh"
      - "grc"
      - "gre" 
      - "gsw"
      - "heb"
      - "hrv"
      - "hun"
      - "ita"
      - "jpn"
      - "kor"
      - "lat"
      - "lav"
      - "lit"
      - "ltz"
      - "mac"
      - "mon"
      - "nap"
      - "nds"
      - "nor"
      - "oci"
      - "pol"
      - "por"
      - "roh"
      - "rom"
      - "rum"
      - "rus"
      - "san"
      - "scn"
      - "sla"
      - "slo"
      - "slv"
      - "scn"
      - "srp"
      - "dsb"
      - "hsb"
      - "spa"
      - "srp"
      - "swe"
      - "tib"
      - "tur"
      - "ukr"
      - "vie"
      - "wel"
      - "wen"
      - "yid"
      - "zxx"
"100": 
  new_window: people
  new_window_field: full_name_equals
  layout: 
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - cols: 2
        editor_partial: subfield_select_codes
        codes_reference: "codes"
    columns: 2
  tag_params:
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
"240": 
  new_window: standard_titles
  new_window_field: title_equals
  layout: 
    fields: 
    - - a
      - type: standard_title
        editor_partial: subfield_secondary
        allow_new: true
    - - o
      - editor_partial: subfield_select_codes
        codes_reference: "240o"
    - - k
      - editor_partial: subfield_select_codes
        codes_reference: "240k"
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "240r"
    - - m
  tag_params:
    240k:
      - "Excerpts"
      - "Sketches"
      - "Fragments"
    240o:
      - "Arr"
    240r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1tt"
      - "2tt"
      - "3tt"
      - "4tt"
      - "5tt"
      - "6tt"
      - "7tt"
      - "8tt"
      - "9tt"
      - "10tt"
      - "11tt"
      - "12tt"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"245": 
  layout: 
    fields: 
    - - a
      - growfield: true
"260": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
    - - e
    - - f
"300": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
    - - c
"340": 
  layout: 
    fields: 
    - - d
      - values: 
        - "Autography"
        - "Computer printout"
        - "Engraving"
        - "Facsimile"
        - "Lithography"
        - "Photoreproductive process"
        - "Reproduction"
        - "Transparency"
        - "Typescript"
        - "Typography"
        - "Woodcut"
        editor_partial: subfield_select
    - - m
      - values: 
        - "2°"
        - "4°"
        - "8°"
        - "12°"
        - "16°"
        - "18°"
        - "20°"
        - "24°"
        editor_partial: subfield_select
"383": 
  layout: 
    fields: 
    - - b   
"500": 
  layout: 
    fields: 
    - - a
      - growfield: true
"508": 
  layout: 
    fields: 
    - - a
      - values: 
        - "Arranger: "
        - "Artist: "
        - "Associated name: "
        - "Binder: "
        - "Bookseller: "
        - "Conceptor: "
        - "Choreographer: "
        - "Collaborator: "
        - "Composer: "
        - "Compiler: "
        - "Conductor: "
        - "Censor: "
        - "Costume designer: "
        - "Dancer: "
        - "Donor: "
        - "Dedicatee: "
        - "Dubious author: "
        - "Editor: "
        - "Engraver: "
        - "Former owner: "
        - "Illustrator: "
        - "Instrumentalist: "
        - "Librettist: "
        - "Lithograph: "
        - "Lyricist: "
        - "Patron: "
        - "Paper maker: "
        - "Production personnel: "
        - "Performer: "
        - "Printer: "
        - "Scribe: "
        - "Translater: "
        - "Vocalist: "
        growfield: true
        editor_partial: subfield_autocomplete
"510": 
  layout:
    fields: 
    - - a
      - values: 
        - "A/I"
        - "A/II"
        - "B/I"
        - "B/II"
        - "B/IV"
        - "B/VI"
        editor_partial: subfield_select
    - - c  
"518": 
  layout: 
    fields: 
    - - a
      - values: 
        - "Composition date: "
        - "First performance date: "
        - "Performance date: "
        editor_partial: subfield_autocomplete
"541": 
  layout: 
    fields: 
    - - c
      - growfield: true
    - - a
    - - d
    - - e
"563": 
  new_window: sources
  layout: 
    fields: 
    - - a
      - growfield: true
    - - u
"588": 
  layout: 
    fields: 
    - - a   
"590": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
      - growfield: true
"592": 
  layout: 
    fields: 
    - - a
"593": 
  layout: 
    fields: 
    - - a
      - values: 
        - Autograph manuscript
        - Possible autograph manuscript
        - Partial autograph
        - Manuscript copy
        - Manuscript copy with autograph annotations
        - Print
        - Print with autograph annotations
        - Print with non-autograph annotations
        - Libretto, handwritten
        - Libretto, printed
        - Treatise, handwritten
        - Treatise, printed
        - Other 
        editor_partial: subfield_select
"594":
  layout: 
    fields: 
    - - b
      - type: source_594b_solr
        field: value
        editor_partial: subfield_secondary
        allow_new: true
    - - c
"595":
  layout: 
    fields: 
    - - a
    - - u
"596":
  new_window: sources
  layout: 
    fields: 
    - - a
      - values: 
        - "A/I"
        - "B/I"
        - "B/II"
        - "B/III"
        - "B/IV"
        - "B/VIII"
        - "B/IX/1"
        - "B/IX/2"
        - "B/XIII"
        - "B/XV"
        - "B/XVII"
        editor_partial: subfield_select
    - - b
    - - c
      - type: source
        editor_partial: subfield_secondary
        only_new_window: true
"597": 
  layout: 
    fields: 
    - - a
"598": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
    - - d
    - - e
    - - f
    - - g
    - - h
    - - i
    - - k
    - - l
    - - m
    - - n
"599": 
  layout: 
    fields: 
    - - a
      - growfield: true
    - - b
      - hidden: true 
"650":
  new_window: standard_terms
  new_window_field: term_equals
  layout: 
    fields: 
    - - a
      - type: standard_term
        editor_partial: subfield_secondary
        allow_new: true
"651":
  new_window: places
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: place
        editor_partial: subfield_secondary
        allow_new: true
"657": 
  new_window: liturgical_feasts
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: liturgical_feast
        editor_partial: subfield_secondary
        allow_new: true
"690": 
  new_window: catalogues
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
        allow_new: false
    - - n
"691":
  new_window: catalogues
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: catalogue
        editor_partial: subfield_secondary
        allow_new: false
    - - n
"700":
  new_window: people
  new_window_field: full_name_equals
  layout:
    fields: 
    - - a
      - type: person
        editor_partial: subfield_secondary
        allow_new: true
    - - d
      - autocomplete_extra: life_dates
    - - j
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - fmo
      - scr
      - cmp
      - arr
      - prf
      - dte
      - lyr
      - lbt
      - trl
      - pbl
      - prt
      - edt
      - ltg
      - egr
      - ill
      - aut
      - oth
      - dub
      - ctb
      - ccp
      - dst
"710":
  new_window: institutions
  new_window_field: name_equals
  layout: 
    fields: 
    - - a
      - type: institution
        editor_partial: subfield_secondary
        allow_new: true
    - - b
    - - g
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
    - - "4"
      - editor_partial: subfield_select_codes
        select_label: "Function"
        codes_reference: "relator_codes"
  tag_params: 
    codes:
      - "Ascertained"
      - "Alleged"
      - "Conjectural"
      - "Doubtful"
      - "Misattributed"
    relator_codes: 
      - pbl
      - fmo
      - dpt
      - dte
      - scr
      - prf
      - prt
      - edt
      - oth
      - evp
      - dst
      - bsl
"730":
  new_window: standard_titles
  new_window_field: title_equals
  layout: 
    fields: 
    - - a
      - type: standard_title
        editor_partial: subfield_secondary
        allow_new: true
    - - o
      - editor_partial: subfield_select_codes
        codes_reference: "730o"
    - - g
      - values: 
        - "RISM"
        - "RDA"
        - "RAK"
        - "ICCU"
        default: "RISM"
        editor_partial: subfield_select
    - - k
      - editor_partial: subfield_select_codes
        codes_reference: "730k"
    - - r
      - editor_partial: subfield_select_codes
        codes_reference: "730r"
    - - n
    - - m
  tag_params:
    730k:
      - "Excerpts"
      - "Sketches"
      - "Fragments"
      - "Inserts"
    730o:
      - "Arr"
      - "Var"
    730r:
      - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
      - "1byz"
      - "2byz"
      - "3byz"
      - "4byz"
      - "5byz"
      - "6byz"
      - "7byz"
      - "8byz"
"740":
  layout: 
    fields: 
    - - a
      - type: source_solr
        field: value
        editor_partial: subfield_secondary
        allow_new: true
    - - n
    - - p
"773":
  new_window: sources
  record_type_helper: get_allowed_record_type
  layout: 
    fields: 
    - - w
      - type: source
        editor_partial: subfield_secondary
        only_new_window: true
"774":
  layout: 
    hide_add_button: true
    fields: 
    - - w
      - editor_partial: subfield_readonly_links
    - - '4'
      - hidden: true
"775":
  new_window: sources
  record_type_helper: get_allowed_record_type_775
  layout: 
    fields: 
    - - w
      - type: source
        editor_partial: subfield_secondary
"787": 
  layout: 
    fields: 
    - - g
    - - n
    - - s
    - - w
"852": 
  new_window: institutions
  layout: 
    fields: 
    - - a
      - type: library
        editor_partial: subfield_secondary
        allow_new: true
    - - e
      - autocomplete_extra: name
    - - b
    - - z
    - - c
      - growfield: true
    - - d
"856": 
  layout: 
    fields: 
    - - u
    - - z
    - - x
      - editor_partial: subfield_select_codes
        codes_reference: "codes"
  tag_params: 
    codes:
      - "IIIF"
      - "Digitalization"
      - "Other"
"930": 
  new_window: works
  new_window_field: title_equals
  layout: 
    fields: 
    - - a
      - type: work
        editor_partial: subfield_secondary
        allow_new: true
"980": 
  layout: 
    fields: 
    - - a
      - cols: 2 
        editor_partial: subfield_select_codes
        codes_reference: "980a"
    - - b
      - cols: 2 
        editor_partial: subfield_select_codes
        codes_reference: "980b"
    - - c
      - cols: 2 
        editor_partial: subfield_select_codes
        codes_reference: "980c"
    columns: 2
  tag_params:
    980a:
      - "RISM"
      - "retro"
      - "import"
    980b:
      - "full"
      - "standard"
      - "brief"
    980c:
      - "examined"
      - "not_examined"

triggers:
  - notify_changes
