--- !map:Settings 
group_order: 
- main_work
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
    - "024"
    - "667"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  control: 
    all_tags: 
    - "040"
    - "001"