--- !map:Settings 
group_order: 
- main_work
- codes
#- people
- incipits
- variants
- relations
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
  codes: 
    all_tags: 
    - "024"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  incipits:
    all_tags:
    - "031"
    all_tag_templates: 
      "031": marc_show/show_incipit
#  people:
#    all_tags:
#    - "500"
  variants:
    all_tags:
    - "400"
#    - "440"
  relations:
    all_tags:
    - "670"
    all_tag_templates:
      "670": people/show_catalogue
  control: 
    all_tags: 
    - "040"
    - "000"
    - "001"
