--- !map:Settings 
group_order: 
- main_work
- codes
- references
- incipits
- relations
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
    - "130"
    - "383"
    - "430"
    - "690"
    - "046"
  references:
    all_tags:
    - "670"
    - "675"
    - "680"
    - "667"
    - "691"
    - "699"
  codes: 
    all_tags: 
    - "024"
    - "380"
  incipits:
    all_tags:
    - "031"
  relations:
    all_tags:
    - "700"
    - "710"
    - "747"
  control: 
    all_tags: 
    - "040"
    - "000"
    - "001"
