--- !map:Settings 
group_order: 
- main_work
- codes
- variants
- references
- incipits
- relations
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
#  people:
#    all_tags:
#    - "500"
  variants:
    all_tags:
    - "400"
#    - "440"
  references:
    all_tags:
    - "670"
    - "680"
  codes: 
    all_tags: 
    - "024"
    - "380"
  incipits:
    all_tags:
    - "031"
  relations:
    all_tags:
    - "700"
    - "747"
  control: 
    all_tags: 
    - "040"
    - "000"
    - "001"
