--- !map:Settings
client:
  "024":
    tags:
      "2": required
      "a": required
  "100":
    tags:
      "0": mandatory
  "130":
    tags:
      "0": required
  "370":
    tags:
      "0": required
  "380":
    tags:
      "0": required
  "500":
    tags:
      "0": required
  "510": 
    tags:
      "0": required
      "4":
        required_if:
          "510": "0"
  "530":
    tags:
      "0": required
  "547":
    tags:
      "0": required
  "670":
    tags:
      "w": required
  "675":
    tags:
      "w": required
  "690":
    tags:
      "0": required
  "691":
    tags:
      "0": required
  "856":
    tags:
      "u": required
      "z": required