--- !map:ActiveSupport::HashWithIndifferentAccess

'000':
  label: records.leader
'001':
  label: records.rism_id_number
'003':
  label: records.control_number_identifier
'005':
  label: records.date_time_last_transaction
01_modern_clefs:
  label: records.common_clefs
'024':
  fields:
    '2':
      label: records.source_number_code
    a:
      label: records.standard_number_code
  label: records.other_standard_identifier
02_mensural_clefs:
  label: records.mensural_clefs
'031':
  fields:
    a:
      label: records.work_number
    b:
      label: records.movement_number
    c:
      label: records.incipit_number
    d:
      label: records.title_movement_tempo
    e:
      label: records.role
    g:
      label: records.clef
    m:
      label: records.voice_instrument
    n:
      label: records.key_signature
    o:
      label: records.time_signature
    p:
      label: records.music_incipit
    q:
      label: records.general_note
    r:
      label: records.key_or_mode
    s:
      label: general.validity
    t:
      label: records.text_incipit
    z:
      label: records.scoring_in_movement
  label: records.incipit
'040':
  fields:
    a:
      label: records.original_cataloging_agency
    b:
      label: records.language_of_cataloging
    c:
      label: records.transcribing_agency
    d:
      label: records.modifying_agency
  label: records.cataloging_source
'046':
  fields:
    k:
      label: records.beginning_or_single_date
    l:
      label: records.end
    z:
      label: records.public_note
  label: records.date_of_creation
'100':
  fields:
    a:
      label: records.composer
    d:
      label: records.life_dates
    m:
      label: records.scoring_summary
    n:
      label: records.opus_thematic_index_number
    r:
      label: records.key_or_mode
    t:
      label: records.title_of_work
  label: records.heading
'130':
  fields:
    a:
      label: records.standardized_title
    m:
      label: records.scoring_summary
    r:
      label: records.key_or_mode
  label: records.standardized_title
'370':
  fields:
    g:
      label: records.place_origin
    i:
      label: records.relationship_information
  label: records.place_of_creation
'377':
  fields:
    a:
      label: records.language_code
  label: records.language_code
'380':
  fields:
    a:
      label: records.subject_heading
  label: records.subject_heading
'383':
  fields:
    a:
      label: records.serial_number
    b:
      label: records.opus_number
  label: records.numeric_designation
'400':
  fields:
    a:
      label: records.heading_composer_name
    d:
      label: records.years_birth_death
    m:
      label: records.scoring_summary
    n:
      label: records.number_part_section
    r:
      label: records.key_or_mode
    t:
      label: records.title_of_work
  label: records.heading
'430':
  fields:
    a:
      label: records.alternative_work_title
    m:
      label: records.scoring_summary
    r:
      label: records.key_or_mode
    s:
      label: records.name_of_part
    p:
      label: records.version_information
  label: records.alternative_work_title
'510':
  fields:
    a:
      label: records.associated_institution
  label: records.associated_institution
'530':
  fields:
    a:
      label: records.work
    g:
      label: records.note
    i:
      label: records.relationship_information
  label: records.related_work
'548':
  fields:
    a:
      label: records.date
    i:
      label: records.type_relationship
  label: records.chronological_term
'550':
  fields:
    a:
      label: records.topical_term
    i:
      label: records.relation
  label: records.topical_term
'551':
  fields:
    a:
      label: records.geographic_name
    i:
      label: records.type
  label: records.geographic_name
'667':
  fields:
    a:
      label: records.internal_note
  label: records.internal_note
'670':
  fields:
    a:
      label: records.source_data_found
    b:
      label: records.information_found
    u:
      label: general.uri
    "9":
      label: general.source_citation
  label: records.source_data_found
'675':
  fields:
    a:
      label: records.source_data_not_found
  label: records.source_data_not_found
'678':
  fields:
    a:
      label: records.additional_bibliographic_information
  label: records.additional_bibliographic_information
'680':
  fields:
    a:
      label: records.general_note
  label: records.general_note
'690':
  fields:
    a:
      label: records.catalog_works
    n:
      label: records.number_page
    s:
      label: records.section
    x:
      label: records.appendix
  label: records.catalog_works
'691':
  fields:
    a:
      label: records.secondary_catalog_works
    n:
      label: records.number_page
    s:
      label: records.section
    x:
      label: records.appendix
  label: records.secondary_catalog_works
'699':
  fields:
    a:
      label: records.work_tag_type
    b:
      label: records.work_tag_note
  label: records.work_tag
'500':
  fields:
    '4':
      label: records.function
    a:
      label: records.name
    d:
      label: records.life_dates
    j:
      label: records.attribution_qualifier
  label: records.related_personal_name
'510':
  fields:
    '4':
      label: records.function
    '8':
      label: records.material_group
    a:
      label: records.institution
    b:
      label: records.department
    g:
      label: records.attribution_qualifier
  label: records.related_institution
'547':
  fields:
    a:
      label: records.liturgical_festival
  label: records.liturgical_festival
'856':
  fields:
    u:
      label: records.external_resource_url
    z:
      label: records.note_external_resource
  label: records.external_resource
'930':
  fields:
    a:
      label: records.work
    i:
      label: records.type_relationship
  label: records.related_work
'981':
  fields:
    "0":
      label: records.original_record
    d:
      label: records.date
  label: records.duplicated_from
Alleged:
  label: records.alleged
Ascertained:
  label: records.ascertained
C+1:
  label: records.c_plus_1
C+2:
  label: records.c_plus_2
C+3:
  label: records.c_plus_3
C+4:
  label: records.c_plus_4
C+5:
  label: records.c_plus_5
C-1:
  label: records.c_minus_1
C-2:
  label: records.c_minus_2
C-3:
  label: records.c_minus_3
C-4:
  label: records.c_minus_4
C-5:
  label: records.c_minus_5
Conjectural:
  label: records.conjectural
F+1:
  label: records.f_plus_1
F+2:
  label: records.f_plus_2
F+3:
  label: records.f_plus_3
F+4:
  label: records.f_plus_4
F+5:
  label: records.f_plus_5
F-1:
  label: records.f_minus_1
F-2:
  label: records.f_minus_2
F-3:
  label: records.f_minus_3
F-4:
  label: records.f_minus_4_bass
F-5:
  label: records.f_minus_5
G+1:
  label: records.g_plus_1
G+2:
  label: records.g_plus_2
G+3:
  label: records.g_plus_3
G+4:
  label: records.g_plus_4
G+5:
  label: records.g_plus_5
G-1:
  label: records.g_minus_1
G-2:
  label: records.g_minus_2_treble
G-3:
  label: records.g_minus_3
G-4:
  label: records.g_minus_4
G-5:
  label: records.g_minus_5
Misattributed:
  label: records.misattributed
"rdau:P60250":
  label: relations_works.P60250
"rdau:P60305":
  label: relations_works.P60305
"rdau:P60216":
  label: relations_works.P60216
"rdau:P60294":
  label: relations_works.P60294
"rdau:P60274":
  label: relations_works.P60274
"rdau:P60242":
  label: relations_works.P60242
"rdau:P60198":
  label: relations_works.P60198
"rdau:P60313":
  label: relations_works.P60313
Verified:
  label: general.verified
administration:
  label: records.administration
arr:
  label: records.arranger
asn:
  label: records.associated_name
aut:
  label: records.author
bn:
  label: records.byname
brother of:
  label: records.brother_of
child of:
  label: records.child_of
att:
  label: records.composer_cross_reference
ccp:
  label: records.conceptor
ctb:
  label: records.co_composer
codes:
  label: records.numbers_code_fields
confused with:
  label: records.confused_with
control:
  label: records.control_fields
da:
  label: records.pseudonym
deprecated:
  label: records.deprecated_fields
do:
  label: records.order_name
doc_abbreviations:
  label: records.abbreviations
doc_aid:
  label: records.aids
doc_cataloguing_collections:
  label: records.cataloging_collection_convoluta
doc_edit_functions:
  label: records.basic_functions
doc_edit_workflow:
  label: general.workflow
doc_editor:
  label: general.editor_help
doc_introduction:
  label: records.introduction
doc_masks:
  label: records.cataloging_forms
doc_tag_index:
  label: general.marc_tag_index
doc_templates:
  label: records.templates
dte:
  label: records.dedicatee
dv:
  label: records.other_searchform
ee:
  label: records.married_name
ef:
  label: records.family_name
father of:
  label: records.father_of
female:
  label: general.female
ff:
  label: records.person_name
g-2:
  label: records.g_minus_2_octave
gg:
  label: records.birth_name
go:
  label: records.place_birth
ha:
  label: records.place_origin
in:
  label: records.initial
incipits:
  label: records.incipits
lbt:
  label: records.librettist
lyr:
  label: records.text_author
main_work:
  label: records.main_entry_fields
male:
  label: general.male
married with:
  label: records.married_with
mo:
  label: records.monogram
mother of:
  label: records.mother_of
notes:
  label: records.note_fields
oth:
  label: records.other_function
other:
  label: records.other
pat:
  label: records.patron
places:
  label: records.countries_places
po:
  label: records.postal_place
references:
  label: records.references_and_notes
related to:
  label: records.related_to
relations:
  label: records.relations
sister of:
  label: records.sister_of
so:
  label: records.place_death
subject:
  label: records.subject_access_fields
tn:
  label: records.baptismal_name
trl:
  label: records.translator
ub:
  label: records.translation
unknown:
  label: records.unknown
variants:
  label: records.title_variants
wl:
  label: records.country_activity
wo:
  label: records.place_activity
wr:
  label: records.region_of_activity
xx:
  label: records.unknown
z:
  label: records.other_form
"needs-revision":
  label: records.work_tag_needs_revision
"incipit-needs-revision":
  label: records.work_tag_incipit_needs_revision
"incipit-replace":
  label: records.work_tag_incipit_replace
"Appendix":
  label: active_admin.status_tag.yes