--- !map:Settings 
group_order: 
- main_work
- codes
#- people
- incipits
- variants
- references
- relations
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
    - "548"
  codes: 
    all_tags: 
    - "024"
    - "380"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  incipits:
    all_tags:
    - "031"
    all_tag_templates: 
      "031": marc_show/show_incipit
#  people:
#    all_tags:
#    - "500"
  variants:
    all_tags:
    - "400"
    all_tag_templates:
      "400": works/show_variants
#    - "440"
  references:
    all_tags:
    - "670"
    - "680"
    all_tag_templates:
      "670": people/show_catalogue
  relations:
    all_tags:
    - "700"
    - "747"
    - "930"
  control: 
    all_tags: 
    - "040"
    - "000"
    - "001"
