--- !map:Settings 
group_order: 
- main_work
- codes
- incipits
- references
- relations
- control
groups:   
  main_work: 
    all_tags: 
    - "100"
    - "130"
    - "383"
    - "430"
    - "690"
    - "046"
    - "370"
    - "377"
    all_tag_templates: 
      "690": marc_show/show_69x_url
  codes: 
    all_tags: 
    - "024"
    - "380"
    all_tag_templates:
      "024": marc_show/show_dnb_link
  incipits:
    all_tags:
    - "031"
    all_tag_templates: 
      "031": marc_show/show_incipit
  references:
    all_tags:
    - "670"
    - "675"
    - "680"
    - "667"
    - "691"
    - "699"
    all_tag_templates: 
      "691": marc_show/show_69x_url
  relations:
    all_tags:
    - "500"
    - "510"
    - "530"
    - "547"
    - "930"
    - "856"
    all_tag_templates:
      "500": works/show_related_person
      "510": marc_show/show_institution 
      "547": works/show_related_feast
      "856": marc_show/show_link
  control: 
    all_tags: 
    - "040"
    - "001"
    - "981"
    all_tag_templates: 
      "981": marc_show/show_duplicated_from