--- 
### Configuration for source
- :id: DefaultSource
  :name: Default Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutDefault
  :filter: 
    default: true
###
- :id: ShowSource
  :name: Show Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "SourceValidation"
###
- :id: MarcSource
  :name: Marc Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutMarc
  :filter:

# Configuration for person
- :id: DefaultPerson
  :name: Default Person
  :model: person
  :labels: 
  - PersonLabels
  :options: 
  - PersonFormOptions
  :layout: 
  - PersonLayoutDefault
  :filter: 
    default: true
###
- :id: ShowPerson
  :name: Show Person
  :model: person
  :labels: 
  - PersonLabels
  :options: 
  - PersonFormOptions
  :layout: 
  - PersonLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "PersonValidation"

# Configuration for institution
- :id: DefaultInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionLabels
  :options: 
  - InstitutionFormOptions
  :layout: 
  - InstitutionLayoutDefault
  :filter:
    default: true 
###
- :id: ShowInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionLabels
  :options: 
  - InstitutionFormOptions
  :layout: 
  - InstitutionLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "InstitutionValidation"

# Configuration for publication
- :id: DefaultPublication
  :name: Publication
  :model: publication
  :labels: 
  - PublicationLabels
  :options: 
  - PublicationFormOptions
  :layout: 
  - PublicationLayoutDefault
  :filter:
    default: true 
###
- :id: ShowPublication
  :name: Publication
  :model: publication
  :labels: 
  - PublicationLabels
  :options: 
  - PublicationFormOptions
  :layout: 
  - PublicationLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "PublicationValidation"
## Holding Record
- :id: DefaultHolding
  :name: Holding
  :model: holding
  :labels: 
  - HoldingBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - HoldingBasicFormOptions
  :layout: 
  - HoldingLayoutDefault
  :filter:
    default: true 
- :id: ShowHolding
  :name: Holding
  :model: holding
  :labels: 
  - HoldingBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - HoldingBasicFormOptions
  :layout: 
  - HoldingLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "HoldingValidation"

# Configuration for work
- :id: DefaultWork
  :name: Work
  :model: work
  :labels: 
  - WorkLabels
  :options: 
  - WorkFormOptions
  :layout: 
  - WorkLayoutDefault
  :filter:
    default: true 
###
- :id: ShowWork
  :name: Work
  :model: work
  :labels: 
  - WorkLabels
  :options: 
  - WorkFormOptions
  :layout: 
  - WorkLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "WorkValidation"

# Configuration for work node
- :id: DefaultWorkNode
  :name: WorkNode
  :model: work_node
  # For now re-use the work labels
  :labels: 
  - WorkLabels
  :options: 
  - WorkNodeFormOptions
  :layout: 
  - WorkNodeLayoutDefault
  :filter:
    default: true 
###
- :id: ShowWorkNode
  :name: WorkNode
  :model: work_node
  # For now re-use the work labels
  :labels: 
  - WorkLabels
  :options: 
  - WorkNodeFormOptions
  :layout: 
  - WorkNodeLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "WorkNodeValidation"

# Configuration for gnd work
- :id: DefaultGndWork
  :name: GndWork
  :model: gnd_work
  # For now re-use the work labels
  :labels: 
  - WorkLabels
  :options: 
  - GndWorkFormOptions
  :layout: 
  - GndWorkLayoutDefault
  :filter:
    default: true
    ###
- :id: ShowGndWork
  :name: GndWork
  :model: gnd_work
  :labels: 
  - WorkLabels
  :options: 
  - GndWorkFormOptions
  :layout: 
  - WorkLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "GndWorkValidation"