--- 
### Configuration for source
- :id: DefaultSource
  :name: Default Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutDefault
  :filter: 
    default: true
###
- :id: ShowSource
  :name: Show Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "SourceValidation"
###
- :id: MarcSource
  :name: Marc Source
  :model: source
  :labels: 
  - SourceLabels
  :options: 
  - SourceFormOptions
  :layout: 
  - SourceLayoutMarc
  :filter:

# Configuration for person
- :id: DefaultPerson
  :name: Default Person
  :model: person
  :labels: 
  - PersonLabels
  :options: 
  - PersonFormOptions
  :layout: 
  - PersonLayoutDefault
  :filter: 
    default: true
###
- :id: ShowPerson
  :name: Show Person
  :model: person
  :labels: 
  - PersonLabels
  :options: 
  - PersonFormOptions
  :layout: 
  - PersonLayoutShow
  :filter:
    show_all: false
    show: true

# Configuration for institution
- :id: DefaultInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionLabels
  :options: 
  - InstitutionFormOptions
  :layout: 
  - InstitutionLayoutDefault
  :filter:
    default: true 
###
- :id: ShowInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionLabels
  :options: 
  - InstitutionFormOptions
  :layout: 
  - InstitutionLayoutShow
  :filter:
    show_all: false
    show: true

# Configuration for catalogue
- :id: DefaultCatalogue
  :name: Catalogue
  :model: catalogue
  :labels: 
  - CatalogueLabels
  :options: 
  - CatalogueFormOptions
  :layout: 
  - CatalogueLayoutDefault
  :filter:
    default: true 
###
- :id: ShowCatalogue
  :name: Catalogue
  :model: catalogue
  :labels: 
  - CatalogueLabels
  :options: 
  - CatalogueFormOptions
  :layout: 
  - CatalogueLayoutShow
  :filter:
    show_all: false
    show: true
  :validation: "CatalogueValidation"
## Holding Record
- :id: DefaultHolding
  :name: Holding
  :model: holding
  :labels: 
  - HoldingBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - HoldingBasicFormOptions
  :layout: 
  - HoldingLayoutDefault
  :filter:
    default: true 
- :id: ShowHolding
  :name: Holding
  :model: holding
  :labels: 
  - HoldingBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - HoldingBasicFormOptions
  :layout: 
  - HoldingLayoutShow
  :filter:
    show_all: false
    show: true
# Configuration for work
- :id: DefaultWork
  :name: Work
  :model: work
  :labels: 
  - WorkLabels
  :options: 
  - WorkFormOptions
  :layout: 
  - WorkLayoutDefault
  :filter:
    default: true 
###
- :id: ShowWork
  :name: Work
  :model: work
  :labels: 
  - WorkLabels
  :options: 
  - WorkFormOptions
  :layout: 
  - WorkLayoutShow
  :filter:
    show_all: false
    show: true
